spring:
  datasource:
    url: 'jdbc:h2:mem:backend'
    username: 'dhbw2go'
    password: 'dhbw2go'
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.H2Dialect'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
youandmeme:
  jwt:
    cookie: 'youandmeme'
    expiration: 3600000
springdoc:
  api-docs:
    path: '/docs'
  swagger-ui:
    path: '/swagger-ui'
dhbw2go:
  jwt:
    cookie: 'dhbw2go'
    expiration: 3600000
