spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MySQL5Dialect'
    properties:
      hibernate:
        current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  api-docs:
    path: '/docs'
  swagger-ui:
    path: '/swagger-ui'
dhbw2go:
  jwt:
    cookie: 'dhbw2go'
    expiration: 3600000
