spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  api-docs:
    path: '/docs'
  swagger-ui:
    path: '/swagger-ui'
dhbw2go:
  jwt:
    expiration:
      token: 3600000
      refresh: 86400000
  openapi:
    development:
      url: 'http://localhost:8080/'
    production:
      url: 'https://api.dhbw2go.de/'
