spring:
  datasource:
    url: 'jdbc:mysql://youandmeme.de:3306/backend'
    username: 'backend'
    password: 'Tn3cYVqDC@P9RovH'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MySQL5Dialect'
    properties:
      hibernate:
        current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
youandmeme:
  jwt:
    cookie: 'youandmeme'
    expiration: 3600000