spring:
  datasource:
    url: 'jdbc:h2:mem:backend'
    username: 'dhbw2go'
    password: 'dhbw2go'
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.H2Dialect'
